### ISSUE TITLE
Selfhosting Guide

### ISSUE THREAD

**Issue by proudparrot2** [ishaan1013/sandbox#24]
Is it possible for you to write a guide on how to self-host this program?
I've filled in the envs the best I could and created tables on the D2 database, but it's still not working, complaining about no such table user.

![CleanShot 2024-05-31 at 19 40 56@2x](https://github.com/ishaan1013/sandbox/assets/71939973/777f4075-863f-4956-992e-929a708e3a22)

**Comment by tarunkumar519** [comment]
i think many people are interested in this. Would be awesome if also there would be a docker deployment?

**Comment by jamesmurdza** [comment]
I've made a guide: https://dev.to/jamesmurdza/how-to-setup-ishaan1013sandbox-locally-503p

Happy to help integrate this into the documentation too.

**Comment by shashank6341** [comment]
hi @jamesmurdza, @ishaan1013 the guide is detailed. Can you assign me on this. I will add them in the Readme.md for easier setup and collaboration.

**Comment by ishaan1013** [comment]
> hi @jamesmurdza, @ishaan1013 the guide is detailed. Can you assign me on this. I will add them in the Readme.md for easier setup and collaboration.

Feel free to make a PR to contribute this, thanks!
