### ISSUE TITLE
Error while opening page http://localhost:3004/dashboard

### ISSUE THREAD

**Issue by laalamrajesh** [ishaan1013/sandbox#27]
After signup getting error
env
```
NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard
```

![image](https://github.com/ishaan1013/sandbox/assets/47312600/4344313f-ff00-44cf-8f13-3440dd9ee57d)

**Comment by jontstaz** [comment]
Same here. Ive deployed everything properly via wrangler, etc and all the .env are populated

**Comment by laalamrajesh** [comment]
Thanks @jontstaz that is the issue. 
From server side i am getting fetch is not defined error i am using node version 14.17.
can you please help what node versions we need to use for each one in the project

**Comment by ishaan1013** [comment]
> Thanks @jontstaz that is the issue. From server side i am getting fetch is not defined error while running the server using command `npm run dev`. i am using node version 14.17. can you please help what node versions we need to use for each one in the project

Using node v20 or newer should work.

**Comment by ishaan1013** [comment]
> Same here. Ive deployed everything properly via wrangler, etc and all the .env are populated
> 
> Edit: ahhh I got it working. You need to run `npm run generate` in the backend/database and push the resulting sql file to the D1 DB first
