### ISSUE TITLE
How does the preview work?

### ISSUE THREAD

**Issue by i-am-henri** [ishaan1013/sandbox#30]
It's less a issue, more a question. How does your preview work? I already understand, that all files are saved in the storage from cloudflare, but how do you proceed? I the preview/index.tsx file, you create an iframe to the local url "localhost:5173" or smthg. like that, but where is the server for that port?

**Comment by anudeepreddy** [comment]
Same question here

**Comment by anudeepreddy** [comment]
I guess I got my answer, the preview works if the server is running locally. The code and the terminal is executed without any isolation. If the server was to be hosted on a remote machine then the preview wouldn't work as there is no provision yet to access the react app running on a remote backend.
